# trigger events
from enum import Enum

BEFORE_UPDATE = "BEFORE UPDATE"
AFTER_UPDATE = "AFTER UPDATE"
BEFORE_INSERT = "BEFORE INSERT"
AFTER_INSERT = "AFTER INSERT"
BEFORE_DELETE = "BEFORE DELETE"
AFTER_DELETE = "AFTER DELETE"
SOURCE_TABLE = "source_table"
SOURCE_ID = "source_id"
DETAILS = "details"

TRIGGER_NO_UPDATE_ON_CREATE = "no_update_on_created"
TRIGGER_SET_TIMESTAMP = "trigger_set_timestamp"

# Field Types
FIELD_TYPE_INTEGER_IDENTITY = "INT GENERATED BY DEFAULT AS IDENTITY"
FIELD_TYPE_DATETIME = "timestamp without time zone DEFAULT CURRENT_TIMESTAMP"
FIELD_TYPE_DATETIME_DEF_NULL = "timestamp without time zone"
FIELD_TYPE_JSONB = "jsonb"
FIELD_TYPE_BYTEA = "bytea"
FIELD_TYPE_INTEGER = "INTEGER"
FIELD_TYPE_STRING = "character varying"
FIELD_TYPE_BOOLEAN = "boolean"
FIELD_TYPE_BOOLEAN_DEFAULT_FALSE = "boolean DEFAULT FALSE"
FIELD_TYPE_BOOLEAN_DEFAULT_TRUE = "boolean DEFAULT TRUE"
FIELD_TYPE_BOOLEAN_DEFAULT_FALSE_NOT_NULL = "boolean DEFAULT FALSE NOT NULL"
FIELD_TYPE_BOOLEAN_DEFAULT_TRUE_NOT_NULL = "boolean DEFAULT TRUE NOT NULL"
FIELD_TYPE_INTEGER_NOT_NULL = "INTEGER NOT NULL"
FIELD_TYPE_STRING_NOT_NULL = "character varying NOT NULL"
FIELD_TYPE_STRING_VARYING_DEF_STANDARD = "character varying(50) DEFAULT 'standard'::character varying"
FIELD_TYPE_STRING_VARYING_DEF_QIKPOD = "character varying(50) DEFAULT 'QIKPOD'::character varying"
FIELD_TYPE_STRING_VARYING_DEF_FREE = "character varying(50) DEFAULT 'free'::character varying"

FIELD_TYPE_STRING_VARYING_DEF_PENDING = "character varying DEFAULT 'pending'"
FIELD_TYPE_INTEGER_DEF_ZERO = "INTEGER DEFAULT 0"
FIELD_TYPE_INTEGER_DEF_THREE = "INTEGER DEFAULT 3"

PROCEDURE_SET_TIMESTAMP = "procedure_set_timestamp"
PROCEDURE_RETAIN_CREATED_DATETIME = "retain_created_datetime"
PROCEDURE_ADD_TO_DELETE_RECORDS = "add_to_deleted_records_table"

# Constraints
CONSTRAINT_PRIMARY_KEY = "PRIMARY KEY"
CONSTRAINT_FOREIGN_KEY = "FOREIGN KEY"
CONSTRAINT_UNIQUE = "UNIQUE"

STR_DELETED_RECORDS_TABLE = "deleted_records"
s_rowcount = 'rowcount'
s_count = 'count'
s_records = 'records'
s_status = 'status'
s_success = 'success'
s_failure = 'failure'
s_status_code = 'status_code'
s_timestamp = "timestamp"
s_message ='message'
s_details = 'details'
s_id ='id'

HTTP_STATUS_CODE_200 = 200
HTTP_STATUS_CODE_404 = 404
HTTP_STATUS_CODE_401 = 401
HTTP_STATUS_CODE_422 = 422
HTTP_STATUS_CODE_500 = 500

s_get = 'get'
s_post = 'post'
s_patch = 'patch'
s_delete = 'delete'

s_admin = 'admin'
s_read = 'read'
s_read_write = 'read_write'

user_permissions = {
            "admin": {s_get,s_post,s_patch,s_delete},
            "read_write": {s_get,s_post,s_patch},
            "read_only": {s_get}
        }


class UserRole(Enum):
    admin: str = s_admin
    read: str = s_read
    read_write: str = s_read_write